# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=snapshots" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=var_log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/16979358-e032-46d6-90ba-a88d555b6e78";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/BA28-39B5";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
