#!/bin/bash
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-kde
killall xdg-desktop-portal-gtk
killall xdg-desktop-portal
/usr/lib64/xdg-desktop-portal-gtk &
sleep 2
/usr/lib64/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib64/xdg-desktop-portal &
