# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_nix" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_snapshots" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_var_log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/478fc3e9-99fa-4c6e-a069-fd19e9b35cdf";
      fsType = "btrfs";
      options = [ "subvol=nixos_swap" ];
    };

  fileSystems."/nixos_boot/efi" =
    { device = "/dev/disk/by-uuid/2A06-3B88";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
