packages = [
	"cosmic-app-library",
	"cosmic-applets",
	"cosmic-bg",
	"cosmic-comp",
	"cosmic-files",
	"cosmic-idle",
	"cosmic-launcher",
	"cosmic-notifications",
	"cosmic-osd",
	"cosmic-panel",
	"cosmic-randr",
	"cosmic-screenshot",
	"cosmic-session",
	"cosmic-settings",
	"cosmic-settings-daemon",
	"cosmic-terminal",
	"cosmic-text-editor",
	"cosmic-workspaces",
	"xdg-desktop-portal-cosmic"
]
