packages = [
	"emacs",
	"emacs-catppuccin-theme-git",
	"emacs-spacemacs-theme-git",
	"emacs-company-mode-git",
	"emacs-compat-git",
	"emacs-consult-git",
	"emacs-go-mode-git",
	"emacs-rust-mode-git",
	"emacs-goto-chg-git",
	"emacs-evil-git",
	"emacs-yasnippet-git",
	"emacs-yasnippet-snippets-git"
]
overlays = [
	"emacs-catppuccin-theme-git",
  	"emacs-spacemacs-theme-git",
  	"emacs-company-mode-git",
	"emacs-compat-git",
	"emacs-consult-git",
	"emacs-go-mode-git",
	"emacs-rust-mode-git",
	"emacs-goto-chg-git",
	"emacs-evil-git",
	"emacs-yasnippet-git",
	"emacs-yasnippet-snippets-git"
]
